"""
atlas_accounts.py — Account + cloud-sync seam for Atlas (local-first).

Design
------
Atlas must run fully offline (it automates the local desktop), so the local
SQLite ``UserMemory`` is always the source of truth.  Cloud is an OPTIONAL
overlay: when ``SUPABASE_URL`` + ``SUPABASE_ANON_KEY`` are present in the
environment, ``AccountManager`` can authenticate against Supabase (email +
password now, Google social login wired later) and sync the signed-in user's
durable data (facts, routines, standing context, prefs) up and down.

Nothing here blocks startup: if the ``supabase`` package or the env config is
missing, ``cloud_available`` is False and every account flow falls back to a
purely local profile.

Supabase setup (one-time, when you're ready to turn on sync)
-----------------------------------------------------------
1. Create a free project at supabase.com, then add to ``.env``::

       SUPABASE_URL=https://<project>.supabase.co
       SUPABASE_ANON_KEY=<anon public key>

2. Run ``SUPABASE_SCHEMA_SQL`` (below) in the Supabase SQL editor to create the
   synced tables with row-level security so each user only sees their own rows.
3. ``pip install supabase`` (already added to requirements.txt, optional).
"""
from __future__ import annotations

import hashlib
import hmac
import logging
import os
import time
from typing import Any, Optional

from atlas_memory import UserMemory

log = logging.getLogger("atlas_accounts")

# Tables synced to the cloud, keyed by their natural unique key locally.
_SYNC_SPEC = {
    "user_facts":     ("category", "key"),
    "routines":       ("name",),
    "global_context": ("content",),
}

# Copy/paste into the Supabase SQL editor to provision the synced schema.
SUPABASE_SCHEMA_SQL = """
-- Each row is owned by the authenticated user (auth.uid()).  RLS keeps users
-- strictly isolated from one another.
create table if not exists user_facts (
    id bigint generated by default as identity primary key,
    owner uuid not null default auth.uid(),
    category text not null,
    key text not null,
    value text not null,
    confidence real not null default 0.75,
    source text not null default 'inferred',
    updated double precision not null default extract(epoch from now()),
    unique(owner, category, key)
);
create table if not exists routines (
    id bigint generated by default as identity primary key,
    owner uuid not null default auth.uid(),
    name text not null,
    goal text not null default '',
    steps_json text not null default '[]',
    notes text not null default '',
    updated double precision not null default extract(epoch from now()),
    unique(owner, name)
);
create table if not exists global_context (
    id bigint generated by default as identity primary key,
    owner uuid not null default auth.uid(),
    content text not null,
    scope text not null default 'global',
    updated double precision not null default extract(epoch from now()),
    unique(owner, content)
);
create table if not exists user_prefs (
    owner uuid primary key default auth.uid(),
    prefs jsonb not null default '{}'::jsonb,
    updated double precision not null default extract(epoch from now())
);
alter table user_facts     enable row level security;
alter table routines       enable row level security;
alter table global_context enable row level security;
alter table user_prefs     enable row level security;
do $$ begin
  perform 1;
  -- owner-only access policies
  execute 'create policy own_facts   on user_facts     for all using (owner = auth.uid()) with check (owner = auth.uid())';
  execute 'create policy own_routines on routines       for all using (owner = auth.uid()) with check (owner = auth.uid())';
  execute 'create policy own_context  on global_context for all using (owner = auth.uid()) with check (owner = auth.uid())';
  execute 'create policy own_prefs    on user_prefs     for all using (owner = auth.uid()) with check (owner = auth.uid())';
exception when duplicate_object then null; end $$;
"""


def supabase_config() -> tuple[str, str]:
    url = (os.environ.get("SUPABASE_URL") or "").strip()
    key = (os.environ.get("SUPABASE_ANON_KEY")
           or os.environ.get("SUPABASE_KEY") or "").strip()
    return url, key


class SupabaseSync:
    """
    Thin, fail-safe wrapper over ``supabase-py``.

    Every method degrades gracefully: if the SDK or config is missing it returns
    a clean failure rather than raising, so the rest of Atlas keeps working
    offline.  Auth uses the user's JWT, so all table reads/writes are scoped by
    row-level security to that user.
    """

    def __init__(self) -> None:
        self._client: Any = None
        self._cloud_id: Optional[str] = None
        self.last_error: str = ""
        self._disabled = False

    @property
    def configured(self) -> bool:
        url, key = supabase_config()
        return bool(url and key)

    @property
    def cloud_id(self) -> Optional[str]:
        return self._cloud_id

    def _ensure_client(self) -> bool:
        if self._disabled:
            return False
        if self._client is not None:
            return True
        if not self.configured:
            return False
        try:
            from supabase import create_client  # type: ignore

            url, key = supabase_config()
            self._client = create_client(url, key)
            return True
        except Exception as exc:
            self.last_error = str(exc)
            self._disabled = True
            log.warning("Supabase unavailable (%s); staying local-only.", exc)
            return False

    # ── auth ──────────────────────────────────────────────────────────────────

    def sign_up(self, email: str, password: str) -> tuple[bool, str]:
        if not self._ensure_client():
            return (False, "Cloud sync isn't configured.")
        try:
            res = self._client.auth.sign_up({"email": email, "password": password})
            user = getattr(res, "user", None)
            if user is None:
                return (False, "Sign-up failed — check the email/password.")
            self._cloud_id = getattr(user, "id", None)
            return (True, "Account created. Check your email to confirm if required.")
        except Exception as exc:
            self.last_error = str(exc)
            return (False, f"Sign-up error: {exc}")

    def sign_in(self, email: str, password: str) -> tuple[bool, str]:
        if not self._ensure_client():
            return (False, "Cloud sync isn't configured.")
        try:
            res = self._client.auth.sign_in_with_password(
                {"email": email, "password": password}
            )
            user = getattr(res, "user", None)
            if user is None:
                return (False, "Incorrect email or password.")
            self._cloud_id = getattr(user, "id", None)
            return (True, "Signed in to the cloud.")
        except Exception as exc:
            self.last_error = str(exc)
            return (False, f"Sign-in error: {exc}")

    def sign_in_with_google(self) -> tuple[bool, str]:
        # Hook reserved for the post-trial OAuth loopback/device-code flow.
        return (False, "Google sign-in is coming soon — use email and password for now.")

    def send_email_otp(self, email: str) -> tuple[bool, str]:
        """Send a one-time login code to ``email`` (Supabase Auth, free tier)."""
        email = (email or "").strip().lower()
        if not email:
            return (False, "Enter your email.")
        if not self._ensure_client():
            return (False, "Cloud sync isn't configured.")
        try:
            self._client.auth.sign_in_with_otp({"email": email})
            return (True, "Check your email for a 6-digit code.")
        except Exception as exc:
            self.last_error = str(exc)
            return (False, f"Couldn't send code: {exc}")

    def verify_email_otp(self, email: str, token: str) -> tuple[bool, str]:
        """Verify an email OTP and establish a cloud session."""
        email = (email or "").strip().lower()
        token = (token or "").strip()
        if not email or not token:
            return (False, "Enter the email and code.")
        if not self._ensure_client():
            return (False, "Cloud sync isn't configured.")
        try:
            res = self._client.auth.verify_otp(
                {"email": email, "token": token, "type": "email"})
            user = getattr(res, "user", None)
            if user is None:
                return (False, "Invalid or expired code.")
            self._cloud_id = getattr(user, "id", None)
            return (True, "Signed in.")
        except Exception as exc:
            self.last_error = str(exc)
            return (False, f"Verification failed: {exc}")

    def sign_out(self) -> None:
        self._cloud_id = None
        if self._client is not None:
            try:
                self._client.auth.sign_out()
            except Exception:
                pass

    # ── data sync (RLS scopes everything to the signed-in user) ────────────────

    def upsert(self, table: str, rows: list[dict]) -> bool:
        if not rows or not self._ensure_client() or not self._cloud_id:
            return False
        try:
            payload = [{**r, "owner": self._cloud_id} for r in rows]
            self._client.table(table).upsert(payload).execute()
            return True
        except Exception as exc:
            self.last_error = str(exc)
            log.warning("Supabase upsert(%s) failed: %s", table, exc)
            return False

    def fetch(self, table: str) -> list[dict]:
        if not self._ensure_client() or not self._cloud_id:
            return []
        try:
            res = (self._client.table(table)
                   .select("*").eq("owner", self._cloud_id).execute())
            return list(getattr(res, "data", []) or [])
        except Exception as exc:
            self.last_error = str(exc)
            log.warning("Supabase fetch(%s) failed: %s", table, exc)
            return []


class AccountManager:
    """
    Local-first account façade used by the UI and StateEngine.

    Local profiles always work.  When cloud is configured, register/login can
    additionally authenticate against Supabase and sync the user's durable data.
    Returns ``(ok, message, user_id)`` so the UI can show precise feedback.
    """

    def __init__(self, memory: Optional[UserMemory] = None) -> None:
        self.memory = memory or UserMemory()
        self.cloud = SupabaseSync()
        self.user_id: Optional[int] = None
        self.email: Optional[str] = None
        self._pending_2fa_uid: Optional[int] = None
        self._pending_2fa_email: str = ""

    @property
    def cloud_available(self) -> bool:
        return self.cloud.configured

    def _persist_name(self, user_id: int, name: str | None) -> None:
        """Store the display name as a durable fact so Atlas knows it at once."""
        clean = (name or "").strip()
        if not (user_id and clean) or "@" in clean:
            return
        try:
            self.memory.set_display_name(user_id, clean)
            self.memory.remember(user_id, "profile", "name", clean,
                                 confidence=0.98, source="profile")
        except Exception:
            pass

    # ── local-only flows ───────────────────────────────────────────────────────

    def register_local(self, name: str, email: str | None = None,
                       password: str | None = None) -> tuple[bool, str, int]:
        ok, msg, uid = self.memory.register(name, email, password)
        if ok:
            self.user_id, self.email = uid, email
            self._persist_name(uid, name)
        return ok, msg, uid

    def login_local(self, name: str, password: str | None = None
                    ) -> tuple[bool, str, int]:
        ok, msg, uid = self.memory.authenticate(name, password)
        if ok:
            self.user_id = uid
            self._persist_name(uid, name)
        return ok, msg, uid

    # ── cloud flows (fall back to local if cloud unconfigured) ──────────────────

    def register_cloud(self, name: str, email: str, password: str
                       ) -> tuple[bool, str, int]:
        if not self.cloud_available:
            return self.register_local(name, email, password)
        ok, msg = self.cloud.sign_up(email, password)
        if not ok:
            return (False, msg, 0)
        # Mirror the cloud account into a local profile and link the cloud id.
        uid = self.memory.create_or_login(name or email, email)
        if self.cloud.cloud_id:
            self.memory.set_pref(uid, "cloud_id", self.cloud.cloud_id)
        self.user_id, self.email = uid, email
        self._persist_name(uid, name)
        self.sync_down(uid)
        self.sync_up(uid)
        return (True, msg, uid)

    def login_cloud(self, email: str, password: str, name: str | None = None
                    ) -> tuple[bool, str, int]:
        if not self.cloud_available:
            return self.login_local(name or email, password)
        ok, msg = self.cloud.sign_in(email, password)
        if not ok:
            return (False, msg, 0)
        uid = self.memory.create_or_login(name or email, email)
        if self.cloud.cloud_id:
            self.memory.set_pref(uid, "cloud_id", self.cloud.cloud_id)
        self.user_id, self.email = uid, email
        if name:
            self._persist_name(uid, name)
        needs, method = self.needs_2fa(uid)
        if needs:
            self._pending_2fa_uid = uid
            self._pending_2fa_email = email
            ok2, msg2 = self.start_2fa_challenge(uid, email)
            if not ok2:
                return (False, msg2, uid)
            return (False, "2FA_REQUIRED", uid)
        self.sync_down(uid)
        self.sync_up(uid)
        return (True, msg, uid)

    def complete_pending_2fa(self, code: str) -> tuple[bool, str, int]:
        uid = getattr(self, "_pending_2fa_uid", None)
        if not uid:
            return (False, "No verification pending.", 0)
        ok, msg = self.verify_2fa(uid, code, getattr(self, "_pending_2fa_email", ""))
        if not ok:
            return (False, msg, uid)
        self._pending_2fa_uid = None
        self.sync_down(uid)
        self.sync_up(uid)
        return (True, "Signed in.", uid)

    def login_otp_cloud(self, email: str, token: str,
                        name: str | None = None) -> tuple[bool, str, int]:
        """Passwordless cloud sign-in via email OTP."""
        if not self.cloud_available:
            return (False, "Email codes require cloud sync.", 0)
        ok, msg = self.cloud.verify_email_otp(email, token)
        if not ok:
            return (False, msg, 0)
        uid = self.memory.create_or_login(name or email.split("@")[0], email)
        if self.cloud.cloud_id:
            self.memory.set_pref(uid, "cloud_id", self.cloud.cloud_id)
        self.user_id, self.email = uid, email.strip().lower()
        if name:
            self._persist_name(uid, name)
        self.sync_down(uid)
        self.sync_up(uid)
        return (True, msg, uid)

    # ── Security / 2FA (stored in user prefs.security) ────────────────────────

    @staticmethod
    def _sec(user_id: int, memory: UserMemory) -> dict:
        prefs = memory.get_prefs(user_id)
        sec = prefs.get("security")
        return dict(sec) if isinstance(sec, dict) else {}

    @staticmethod
    def _save_sec(user_id: int, memory: UserMemory, sec: dict) -> None:
        memory.set_pref(user_id, "security", sec)

    def get_security(self, user_id: int) -> dict:
        sec = self._sec(user_id, self.memory)
        return {
            "twofa_enabled": bool(sec.get("twofa_enabled", False)),
            "twofa_method": sec.get("twofa_method") or "none",
            "has_totp": bool(sec.get("totp_secret")),
            "has_app_lock": bool(sec.get("app_lock_hash")),
            "pause_sensing": bool(sec.get("pause_sensing", False)),
        }

    def set_security(self, user_id: int, **kwargs) -> None:
        sec = self._sec(user_id, self.memory)
        sec.update(kwargs)
        self._save_sec(user_id, self.memory, sec)

    def needs_2fa(self, user_id: int) -> tuple[bool, str]:
        sec = self._sec(user_id, self.memory)
        if not sec.get("twofa_enabled"):
            return (False, "none")
        method = sec.get("twofa_method") or "email"
        return (True, method)

    def start_2fa_challenge(self, user_id: int, email: str) -> tuple[bool, str]:
        """Begin second factor — sends email code or prompts for TOTP."""
        ok, method = self.needs_2fa(user_id)
        if not ok:
            return (True, "none")
        if method == "totp":
            return (True, "Enter the 6-digit code from your authenticator app.")
        if method == "email":
            if not email:
                prof = self.memory.get_profile(user_id)
                email = (prof.get("email") or "").strip()
            if not email:
                return (False, "No email on file for 2FA.")
            return self.cloud.send_email_otp(email)
        return (False, f"Unknown 2FA method: {method}")

    def verify_2fa(self, user_id: int, code: str, email: str = "") -> tuple[bool, str]:
        ok, method = self.needs_2fa(user_id)
        if not ok:
            return (True, "OK")
        code = (code or "").strip()
        if method == "totp":
            sec = self._sec(user_id, self.memory)
            secret = sec.get("totp_secret") or ""
            if not secret:
                return (False, "Authenticator not set up.")
            try:
                import pyotp
                if pyotp.TOTP(secret).verify(code, valid_window=1):
                    return (True, "Verified.")
                return (False, "Incorrect code.")
            except Exception as exc:
                return (False, f"TOTP error: {exc}")
        if method == "email":
            prof = self.memory.get_profile(user_id)
            em = (email or prof.get("email") or "").strip().lower()
            if not em:
                return (False, "No email for verification.")
            ok2, msg = self.cloud.verify_email_otp(em, code)
            return (ok2, msg)
        return (False, "Unknown 2FA method.")

    def setup_totp_secret(self, user_id: int) -> tuple[str, str]:
        """Generate a new TOTP secret + provisioning URI (do not enable until confirmed)."""
        import pyotp
        prof = self.memory.get_profile(user_id)
        label = prof.get("email") or prof.get("name") or f"user{user_id}"
        secret = pyotp.random_base32()
        uri = pyotp.totp.TOTP(secret).provisioning_uri(
            name=label, issuer_name="Atlas")
        sec = self._sec(user_id, self.memory)
        sec["totp_pending_secret"] = secret
        self._save_sec(user_id, self.memory, sec)
        return secret, uri

    def confirm_totp_setup(self, user_id: int, code: str) -> tuple[bool, str]:
        sec = self._sec(user_id, self.memory)
        secret = sec.pop("totp_pending_secret", None)
        if not secret:
            return (False, "No pending authenticator setup.")
        try:
            import pyotp
            if not pyotp.TOTP(secret).verify(code.strip(), valid_window=1):
                sec["totp_pending_secret"] = secret
                self._save_sec(user_id, self.memory, sec)
                return (False, "Incorrect code — try again.")
            sec["totp_secret"] = secret
            sec["twofa_enabled"] = True
            sec["twofa_method"] = "totp"
            self._save_sec(user_id, self.memory, sec)
            return (True, "Authenticator app linked.")
        except Exception as exc:
            return (False, str(exc))

    def enable_email_2fa(self, user_id: int) -> tuple[bool, str]:
        prof = self.memory.get_profile(user_id)
        if not prof.get("email"):
            return (False, "Add an email to your profile first.")
        sec = self._sec(user_id, self.memory)
        sec["twofa_enabled"] = True
        sec["twofa_method"] = "email"
        sec.pop("totp_secret", None)
        self._save_sec(user_id, self.memory, sec)
        return (True, "Email two-step verification enabled.")

    def disable_2fa(self, user_id: int) -> None:
        sec = self._sec(user_id, self.memory)
        sec["twofa_enabled"] = False
        sec["twofa_method"] = "none"
        sec.pop("totp_secret", None)
        sec.pop("totp_pending_secret", None)
        self._save_sec(user_id, self.memory, sec)

    def set_app_lock_pin(self, user_id: int, pin: str) -> tuple[bool, str]:
        pin = (pin or "").strip()
        if len(pin) < 4 or not pin.isdigit():
            return (False, "PIN must be at least 4 digits.")
        h = UserMemory._hash_password(pin)
        sec = self._sec(user_id, self.memory)
        sec["app_lock_hash"] = h
        self._save_sec(user_id, self.memory, sec)
        return (True, "App lock PIN set.")

    def verify_app_lock_pin(self, user_id: int, pin: str) -> bool:
        sec = self._sec(user_id, self.memory)
        stored = sec.get("app_lock_hash")
        if not stored:
            return True
        stored = str(stored)
        if "$" in stored:
            return UserMemory._verify_password(pin or "", stored)
        # Legacy installs: constant salt + bare hex digest.
        legacy = hashlib.pbkdf2_hmac(
            "sha256", (pin or "").encode(), b"atlas-lock", 120_000,
        ).hex()
        return hmac.compare_digest(legacy, stored)

    def change_password_local(self, user_id: int, old: str, new: str) -> tuple[bool, str]:
        prof = self.memory.get_profile(user_id)
        if not prof:
            return (False, "User not found.")
        with self.memory._connect() as conn:
            row = conn.execute(
                "SELECT password_hash FROM users WHERE id = ?",
                (int(user_id),),
            ).fetchone()
        has_local_password = bool(row and row["password_hash"])
        cloud_id = str(self.memory.get_prefs(user_id).get("cloud_id") or "").strip()
        if not has_local_password and cloud_id:
            return (
                False,
                "This account uses cloud sign-in — change your password at your "
                "account provider.",
            )
        if not has_local_password:
            return (False, "This profile has no local password set.")
        ok, _msg, _ = self.memory.authenticate(prof.get("name", ""), old)
        if not ok:
            return (False, "Current password is incorrect.")
        self.memory.update_profile(user_id, password=new)
        return (True, "Password updated.")

    def sign_out(self) -> None:
        self.cloud.sign_out()
        self.user_id = None
        self.email = None

    # ── sync (best-effort; no-op offline) ───────────────────────────────────────

    def sync_up(self, user_id: int) -> bool:
        if not (self.cloud_available and self.cloud.cloud_id):
            return False
        ok = True
        facts = self.memory.recall(user_id, min_confidence=0.0)
        if facts:
            ok &= self.cloud.upsert("user_facts", [
                {"category": f["category"], "key": f["key"], "value": f["value"],
                 "confidence": f["confidence"], "source": f["source"],
                 "updated": f.get("created", time.time())}
                for f in facts
            ])
        routines = self.memory.list_routines(user_id)
        full = [self.memory.get_routine(user_id, r["id"]) for r in routines]
        if full:
            ok &= self.cloud.upsert("routines", [
                {"name": r["name"], "goal": r.get("goal", ""),
                 "steps_json": r.get("steps_json", "[]"),
                 "notes": r.get("notes", ""), "updated": time.time()}
                for r in full if r
            ])
        ctx = self.memory.list_context(user_id)
        if ctx:
            ok &= self.cloud.upsert("global_context", [
                {"content": c["content"], "scope": c.get("scope", "global"),
                 "updated": c.get("created", time.time())}
                for c in ctx
            ])
        prefs = self.memory.get_prefs(user_id)
        if prefs:
            ok &= self.cloud.upsert("user_prefs", [{"prefs": prefs,
                                                    "updated": time.time()}])
        return ok

    def sync_down(self, user_id: int) -> bool:
        if not (self.cloud_available and self.cloud.cloud_id):
            return False
        for row in self.cloud.fetch("user_facts"):
            self.memory.remember(user_id, row.get("category", "general"),
                                 row.get("key", "note"), row.get("value", ""),
                                 float(row.get("confidence", 0.75)),
                                 source=row.get("source", "inferred"))
        import json as _json
        for row in self.cloud.fetch("routines"):
            try:
                steps = _json.loads(row.get("steps_json", "[]"))
            except Exception:
                steps = []
            self.memory.save_routine(user_id, row.get("name", "routine"),
                                     row.get("goal", ""), steps,
                                     row.get("notes", ""))
        existing = {c["content"] for c in self.memory.list_context(user_id)}
        for row in self.cloud.fetch("global_context"):
            content = row.get("content", "")
            if content and content not in existing:
                self.memory.add_context(user_id, content, row.get("scope", "global"))
        for row in self.cloud.fetch("user_prefs"):
            prefs = row.get("prefs") or {}
            if isinstance(prefs, dict):
                for k, v in prefs.items():
                    self.memory.set_pref(user_id, k, v)
        return True
