-- Atlas cloud-sync schema for Supabase.
-- Run this ONCE in your Supabase project: Dashboard > SQL Editor > New query >
-- paste all of this > Run.  It creates the four synced tables with row-level
-- security so each signed-in user can only ever see their own rows.

create table if not exists user_facts (
    id bigint generated by default as identity primary key,
    owner uuid not null default auth.uid(),
    category text not null,
    key text not null,
    value text not null,
    confidence real not null default 0.75,
    source text not null default 'inferred',
    updated double precision not null default extract(epoch from now()),
    unique(owner, category, key)
);

create table if not exists routines (
    id bigint generated by default as identity primary key,
    owner uuid not null default auth.uid(),
    name text not null,
    goal text not null default '',
    steps_json text not null default '[]',
    notes text not null default '',
    updated double precision not null default extract(epoch from now()),
    unique(owner, name)
);

create table if not exists global_context (
    id bigint generated by default as identity primary key,
    owner uuid not null default auth.uid(),
    content text not null,
    scope text not null default 'global',
    updated double precision not null default extract(epoch from now()),
    unique(owner, content)
);

create table if not exists user_prefs (
    owner uuid primary key default auth.uid(),
    prefs jsonb not null default '{}'::jsonb,
    updated double precision not null default extract(epoch from now())
);

alter table user_facts     enable row level security;
alter table routines       enable row level security;
alter table global_context enable row level security;
alter table user_prefs     enable row level security;

-- Owner-only access policies (idempotent: safe to re-run).
do $$ begin
  execute 'create policy own_facts    on user_facts     for all using (owner = auth.uid()) with check (owner = auth.uid())';
exception when duplicate_object then null; end $$;
do $$ begin
  execute 'create policy own_routines on routines       for all using (owner = auth.uid()) with check (owner = auth.uid())';
exception when duplicate_object then null; end $$;
do $$ begin
  execute 'create policy own_context  on global_context for all using (owner = auth.uid()) with check (owner = auth.uid())';
exception when duplicate_object then null; end $$;
do $$ begin
  execute 'create policy own_prefs    on user_prefs     for all using (owner = auth.uid()) with check (owner = auth.uid())';
exception when duplicate_object then null; end $$;
